#!/bin/bash -eu
port="$(modelctl get http.port)"
host="$(modelctl get http.host)"
sleep_idle_seconds="$(modelctl get sleep-idle-seconds)"
min_context_size="$(modelctl get min-context-size)"
model_name=$("$SNAP_NAME" model --format=json | jq -r '.name')

extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

exec llama-server \
  --model "$MODEL_FILE" \
  --alias "$model_name" \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  --sleep-idle-seconds "$sleep_idle_seconds" \
  --fit-ctx "$min_context_size" \
  "${extra_args[@]}" \
  "$@"
